config_path: /home/user/Desktop/example.yaml
seed: 0
save_path: /home/user/Desktop/Results/
device: cpu
data_dir: /home/user/Desktop/DataSets/
window_size: 128
mode: debug
norm: None

ENV_info:
    input_dim: null
    state_dim: null
    action_dim: null
    action_space: null
    obs_shape: null

# Simple Testing Environment
STE_cfg:
    seed: ${seed}
    mode: ${mode}
    norm: ${norm}
    save_path: ${save_path}
    window_size: ${window_size}
    stats_path: None
    kwd: None
    max_loss: None
    repeat: None
    noise_penalty: 0.001
    data_divisions: [0.9, 0.1]
    action_mode: soft
    deadlim: [0.1, 0.1]

DAAC_cfg:
    seed: ${seed}
    device: ${device}

    # PPO args
    env_name: STEnv
    lr: 0.0005
    eps: 1e-05
    alpha: 0.99
    gamma: 0.999
    gae_lambda: 0.95
    entropy_coef: 0.01
    value_loss_coef: 0.5
    max_grad_norm: 0.5
    num_processes: 16
    num_steps: 256
    ppo_epoch: 1
    num_mini_batch: 8
    clip_param: 0.2
    log_interval: 10
    num_env_steps: 2500
    algo: idaac
    hidden_size: 256
    log_dir: ${save_path}
    save_path: ${save_path}

    # DAAC args
    value_epoch: 9
    value_freq: 1
    adv_loss_coef: 0.25

    # IDAAC args
    use_nonlinear_clf: False
    clf_hidden_size: 4
